AWSTemplateFormatVersion: '2010-09-09'
Description: necessary roles and policies
Parameters:
  codeRepoDesc:
    Type: String
    Default: Source code for the ECS blue/green demo
    Description: CodeCommit repository for the ECS blue/green demo
Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
    # Metadata:
    #   aws:cdk:path: BlueGreenContainerImageStack/EcsBlueGreenRoles/ecsTaskRoleForWorkshop/Resource
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
    # Metadata:
    #   aws:cdk:path: BlueGreenContainerImageStack/EcsBlueGreenRoles/codeBuildServiceRole/Resource
  CodeBuildServiceRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - ecr:GetAuthorizationToken
              - ecr:BatchCheckLayerAvailability
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
              - s3:Get*
              - s3:List*
              - s3:PutObject
              - secretsmanager:GetSecretValue
            Effect: Allow
            Resource: "*"
          - Action: codecommit:GitPull
            Effect: Allow
            Resource:
              Fn::GetAtt:
                - CodeCommitRepo
                - Arn
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: CodeBuildProject
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: CodeBuildProject
                    - :*
          - Action:
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
              - codebuild:BatchPutTestCases
              - codebuild:BatchPutCodeCoverages
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                - - "arn:"
                  - Ref: AWS::Partition
                  - ":codebuild:"
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - :report-group/
                  - Ref: CodeBuildProject
                  - -*
        Version: "2012-10-17"
      PolicyName: CodeBuildServiceRolePolicy
      Roles:
        - Ref: CodeBuildServiceRole
    # Metadata:
    #   aws:cdk:path: BlueGreenContainerImageStack/EcsBlueGreenRoles/codeBuildServiceRole/DefaultPolicy/Resource
  ECRrepo:
    Type: AWS::ECR::Repository
    Properties:
      ImageScanningConfiguration:
        ScanOnPush: true
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    # Metadata:
    #   aws:cdk:path: BlueGreenContainerImageStack/EcsBlueGreenBuildImage/ecrRepo/Resource
  CodeCommitRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: nginx-sample
      RepositoryDescription:
        Ref: codeRepoDesc
    # Metadata:
    #   aws:cdk:path: BlueGreenContainerImageStack/EcsBlueGreenBuildImage/codeRepo/Resource
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: REPOSITORY_URI
            Type: PLAINTEXT
            Value:
              Fn::Join:
                - ""
                - - Fn::Select:
                      - 4
                      - Fn::Split:
                          - ":"
                          - Fn::GetAtt:
                              - ECRrepo
                              - Arn
                  - .dkr.ecr.
                  - Fn::Select:
                      - 3
                      - Fn::Split:
                          - ":"
                          - Fn::GetAtt:
                              - ECRrepo
                              - Arn
                  - "."
                  - Ref: AWS::URLSuffix
                  - /
                  - Ref: ECRrepo
          - Name: TASK_EXECUTION_ARN
            Type: PLAINTEXT
            Value:
              Fn::GetAtt:
                - TaskExecutionRole
                - Arn
        Image: aws/codebuild/standard:5.0
        ImagePullCredentialsType: CODEBUILD
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildServiceRole
          - Arn
      Source:
        Location:
          Fn::GetAtt:
            - CodeCommitRepo
            - CloneUrlHttp
        Type: CODECOMMIT
      Description: Code build project for the application
      EncryptionKey: alias/aws/s3
      SourceVersion: main
